# config.yaml

# homology target
target_fasta:             "../../data/reference/GCF_000003195.3_Sorghum_bicolor_NCBIv3_protein.faa"

# reference files directories
gene2accession:           "../../data/reference/gene2accession.gz"
reference_kegg_dir:       "../../data/reference/KEGG"

# results directories
results_homology_dir:     "../../results/hmm_homology"
results_network_dir:      "../../results/gene_network"
results_kegg_dir:         "../../results/kegg"
results_ko_dir:           "../../results/by_ko"

# for pathway data in KEGG scraping module
species:    "atted-plants"
pathway:    "map00020" # "map00660"

# blast settings in HMM module
seeds:
  prpF:  "../../data/input/prpF.faa"
  ais:   "../../data/input/ais.faa"
  adi1:  "../../data/input/adi1.faa"

taxids:          33090        # 33090 viridiplantae(or 3398 for Magnoliopsida/flowering plants)
max_target_seqs: 100          # Increased to capture more diverse hits
dbs:
  nr:     "nr"
  refseq: "refseq_protein"
