# workflows/hmm_homology/config.yaml
seed_fasta:    "../../data/input/prpF.faa"
target_fasta:  "../../data/reference/GCF_000003195.3_Sorghum_bicolor_NCBIv3_protein.faa"
gene2accession: "../../data/reference/gene2accession.gz"
prefix:        "prpF"
results_dir:   "../../results/hmm_homology"
coverage:      0.5          # reserved for future BLAST qcovs filtering
taxids:        33090        # Viridiplantae NCBI taxon ID
max_target_seqs: 10
threads:       4