# configs/config.yaml

# wdir: "/Users/daffa/Documents/Work/jspp67_bioinf" # MacStudio
wdir: "/Users/daffaaprilio/Documents/Work/jspp67_bioinf" # MacBook

# homology target
target_fasta:             "data/reference/GCF_000003195.3_Sorghum_bicolor_NCBIv3_protein.faa"

# reference files directories
gene2accession:           "data/reference/gene2accession.gz"
reference_kegg_dir:       "data/reference/KEGG"

# results directories
results_homology_dir:     "results/hmm_homology"
results_network_dir:      "results/gene_network"
results_kegg_dir:         "results/kegg"
results_ko_dir:           "results/by_ko"

# for pathway data in KEGG scraping module
species:    "atted-plants"
pathways:   "map00020 map00660"

# blast settings in HMM module
seeds:
  prpF:  "data/input/prpF.faa"
  ais:   "data/input/ais.faa"
  adi1:  "data/input/adi1.faa"

taxids:          33090        # 33090 viridiplantae(or 3398 for Magnoliopsida/flowering plants)
max_target_seqs: 100          # Increased to capture more diverse hits
dbs:
  nr:     "nr"
  refseq: "refseq_protein"

# parameters for co-expression network construction module
coex_dir:     data/reference/sbi_coex
minZ_score:   4.0
top_K_genes:  10
